### ISSUE TITLE
compile error on PHP 7.3

### ISSUE THREAD

**Issue by Joungkyun** [OOPS-ORG-PHP/mod_geoip#1]
## Bug Environments
- [x] Product Version : 2.0.1
- [x] PHP Version:  7.3
- [x] PHP SAPI: all

## Describe the bug

If build on php 7.3, follow errors occurs:

```bash
In file included from /usr/include/php73/Zend/zend.h:27:0,
                 from /usr/include/php73/main/php.h:34,
                 from /root/work/github/php/aaa/php_geoip.c:51:
/root/work/github/php/aaa/php_geoip.c: In function 'zif_geoip_id_by_name':
/usr/include/php73/Zend/zend_types.h:792:24: error: expected expression before 'do'
 #define ZVAL_ARR(z, a) do {      \
                        ^
/usr/include/php73/Zend/zend_API.h:386:28: note: in expansion of macro 'ZVAL_ARR'
 #define array_init(arg)    ZVAL_ARR((arg), zend_new_array(0))
                            ^
/root/work/github/php/aaa/php_geoip.c:622:7: note: in expansion of macro 'array_init'
  if ( array_init (return_value) == FAILURE ) {
       ^
/root/work/github/php/aaa/php_geoip.c: In function 'zif_geoip_record_by_name':
/usr/include/php73/Zend/zend_types.h:792:24: error: expected expression before 'do'
 #define ZVAL_ARR(z, a) do {      \
                        ^
/usr/include/php73/Zend/zend_API.h:386:28: note: in expansion of macro 'ZVAL_ARR'
 #define array_init(arg)    ZVAL_ARR((arg), zend_new_array(0))
                            ^
/root/work/github/php/aaa/php_geoip.c:692:7: note: in expansion of macro 'array_init'
  if ( array_init (return_value) == FAILURE ) {
       ^
make: *** [php_geoip.lo] 오류 1

```

## To Reproduce

```bash
[user@host mod_geoip-2.0.1]$ phpize && ./configure && make
```

## Expected behavior

```bash
Build complete.
Don't forget to run 'make test'.
```
